/* =========================================================================
   Oberoi Enterprise — catalogue data
   Transcribed from the printed catalogue (6-4-24). Edit here to change
   site info, categories and products everywhere on the site.
   ========================================================================= */

export const SITE = {
  name: "Oberoi Enterprise",
  tagline: "Manufacturers & Importers of Exclusive Hardware Fittings",
  motto: "name stand's quality",
  email: "virvar.oberoi@gmail.com",
  phone: "+91 98925 99280",
  phones: ["+91 98925 99280", "+91 99306 45638", "+91 98673 82976"],
  whatsapp: "919892599280",
  address: "116, Gurunanak Udyog Bhavan, LBS Marg, Bhandup (W), Mumbai 400 078, India",
  pdf: "uploads/Oberoi Ent catloge 6-4-24.pdf",
};

export const CATEGORIES = [
  { slug: "door-magnets", no: "01", name: "Door Magnets", img: "assets/cat-magnets.jpg", page: 3,
    blurb: "Round, 888, 919, 938, 804 and hydraulic door magnets in SS, AB and CP finishes." },
  { slug: "door-fittings", no: "02", name: "Door Fittings", img: "assets/cat-doorfittings.jpg", page: 4,
    blurb: "Floor stoppers, push-pull magnets, safety chains, closers, display rods and protectors." },
  { slug: "locks", no: "03", name: "Locks", img: "assets/cat-locks.jpg", page: 6,
    blurb: "Biscuit, popat, glass, multi, cam and window locks — plus iron, brass and SS pad locks." },
  { slug: "hinges", no: "04", name: "Hinges", img: "assets/cat-hinges.jpg", page: 7,
    blurb: "Hydraulic, auto-close, glass, pivot, bearing, flush and soft-closing spring hinges." },
  { slug: "channels-wheels", no: "05", name: "Channels, Wheels & Gas Pumps", img: "assets/cat-channels.jpg", page: 8,
    blurb: "Telescopic channels, soft-close wheel systems, gas pumps, friction hinges and brackets." },
  { slug: "kitchen-zalli", no: "06", name: "Aluminium Kitchen Zalli", img: "assets/cat-zalli.jpg", page: 9,
    blurb: "Ventilation zalli and bend-type kitchen jali in SS brush, black and rosegold." },
  { slug: "conceal-fittings", no: "07", name: "Conceal Fittings", img: "assets/cat-conceal.jpg", page: 10,
    blurb: "Conceal handles, oval / square / round conceals, plates, rings and tappers." },
  { slug: "glass-door-handles", no: "08", name: "Glass Door Handles", img: "assets/cat-handles.jpg", page: 12,
    blurb: "'H', 'D' and 'S' type handles — round, square and crafted AB, with-lock options." },
  { slug: "knobs", no: "09", name: "Knobs", img: "assets/cat-knobs.jpg", page: 14,
    blurb: "Crystal, cateye, mirror, cut-design and colour knobs plus royal and rose series." },
  { slug: "glass-fittings", no: "10", name: "Glass Fittings", img: "assets/cat-glassfittings.jpg", page: 15,
    blurb: "Mirror caps, sumo and partition brackets, glass studs, 'L' vacuums and clamps." },
  { slug: "main-door-handles", no: "11", name: "Main Door Handles", img: "assets/cat-maindoor.jpg", page: 18,
    blurb: "Classic and 98-series main door handles plus square 'D' and 'H' pull handles." },
  { slug: "cabinet-handles", no: "12", name: "Cabinet Handles", img: "assets/cat-cabinet.jpg", page: 20,
    blurb: "Cabinet handle series in 96–224 mm plus the SS patti and knurled handle range." },
  { slug: "general-hardware", no: "13", name: "General Hardware", img: "assets/cat-general.jpg", page: 13,
    blurb: "PVC fittings, cable managers, latches, sofa legs, datta, buffers and curtain hardware." },
];

/* Each product: slug, name, category, codes (display), finishes, sizes,
   blurb, variants[{code, desc}], featured */
export const PRODUCTS = [
  /* ------------- DOOR MAGNETS ------------- */
  { slug: "round-magnet", name: "Round Magnet", category: "door-magnets", codes: "M1 – M3", featured: true,
    finishes: "SS · AB", sizes: "L / H bodies",
    blurb: "The classic round door magnet — low and high body heights, with antique brass option.",
    variants: [
      { code: "M1", desc: "Round Magnet (L)" },
      { code: "M2", desc: "Round Magnet (H)" },
      { code: "M3", desc: "Round Magnet AB (H)" },
    ] },
  { slug: "series-magnets", name: "888 / 919 / 938 Magnet", category: "door-magnets", codes: "M4 – M9",
    finishes: "SS · AB", sizes: "Standard",
    blurb: "Our best-selling numbered magnet series — each pattern in stainless steel and antique brass.",
    variants: [
      { code: "M4", desc: "888 Magnet SS" }, { code: "M5", desc: "888 Magnet AB" },
      { code: "M6", desc: "919 Magnet SS" }, { code: "M7", desc: "919 Magnet AB" },
      { code: "M8", desc: "938 Magnet SS" }, { code: "M9", desc: "938 Magnet AB" },
    ] },
  { slug: "cp-magnets", name: "500 / 304 Magnet CP", category: "door-magnets", codes: "M10 · M21",
    finishes: "CP (chrome)", sizes: "Standard",
    blurb: "Chrome-plated magnets for polished, modern doors.",
    variants: [
      { code: "M10", desc: "500 Magnet CP" },
      { code: "M21", desc: "304 Magnet CP" },
    ] },
  { slug: "804-magnet", name: "804 Magnet & Plate", category: "door-magnets", codes: "M11 – M13",
    finishes: "SS · AB (plate)", sizes: "Standard",
    blurb: "804 magnet with matching mounting plates in SS and antique brass.",
    variants: [
      { code: "M11", desc: "804 Magnet SS" },
      { code: "M12", desc: "804 Magnet Plate SS" },
      { code: "M13", desc: "804 Magnet Plate AB" },
    ] },
  { slug: "808-magnet", name: "808 Magnet", category: "door-magnets", codes: "M14 – M15",
    finishes: "SS · AB", sizes: "Standard",
    blurb: "Compact 808 pattern magnet in stainless steel and antique brass.",
    variants: [
      { code: "M14", desc: "808 Magnet SS" }, { code: "M15", desc: "808 Magnet AB" },
    ] },
  { slug: "303-632-magnets", name: "303 / 632 / 634 Magnet", category: "door-magnets", codes: "M16 – M20",
    finishes: "CP · AB", sizes: "Standard",
    blurb: "Decorative magnet patterns in chrome and antique brass.",
    variants: [
      { code: "M16", desc: "303 Magnet CP" }, { code: "M17", desc: "303 Magnet AB" },
      { code: "M18", desc: "632 Magnet CP" }, { code: "M19", desc: "632 Magnet AB" },
      { code: "M20", desc: "634 Magnet AB" },
    ] },
  { slug: "516-932-magnets", name: "516 / 932 / SQ Magnet", category: "door-magnets", codes: "M22 – M25",
    finishes: "SS · AB", sizes: "Standard · square",
    blurb: "516 and 932 patterns plus the square-body SQ magnet.",
    variants: [
      { code: "M22", desc: "516 Magnet SS" }, { code: "M23", desc: "516 Magnet AB" },
      { code: "M24", desc: "932 Magnet AB" }, { code: "M25", desc: "SQ Magnet" },
    ] },
  { slug: "hydraulic-magnet", name: "Hydraulic Magnet", category: "door-magnets", codes: "M-26 – M-30", featured: true,
    finishes: "Black · Rose Gold · SS · AB", sizes: "800 / 929 / 516 / 919 patterns",
    blurb: "Soft-action hydraulic door magnets — premium black and rose gold finishes.",
    variants: [
      { code: "M-26", desc: "Hydraulic Magnet" },
      { code: "M-28", desc: "516 Black / Rose Gold · 919 Black / Rose Gold" },
      { code: "M-29", desc: "929 SS / AB" },
      { code: "M-30", desc: "800 Black / Rose Gold" },
    ] },

  /* ------------- DOOR FITTINGS ------------- */
  { slug: "floor-door-stopper", name: "Floor Door Stopper", category: "door-fittings", codes: "FD-1 · FD-2 · A-05 · A-06", featured: true,
    finishes: "SS · AB · PVC", sizes: "Standard · 220 pattern",
    blurb: "Floor-mounted stoppers — plain and magnet types, plus the 220 series.",
    variants: [
      { code: "FD-1", desc: "Floor Door Stopper SS & AB" },
      { code: "FD-2", desc: "Floor Door Stopper Magnet" },
      { code: "A-05", desc: "220 SS / AB" },
      { code: "A-06", desc: "SS Floor Stopper" },
    ] },
  { slug: "push-pull-magnet", name: "Push Pull Magnet", category: "door-fittings", codes: "PP-1 – PP-4",
    finishes: "White · Black · SS · PVC", sizes: "Round · square · big",
    blurb: "Push-to-open magnets for handle-less shutters — round and square, in white and black.",
    variants: [
      { code: "PP-1", desc: "Push Pull Round — White & Black" },
      { code: "PP-2", desc: "Push Pull Square — White & Black" },
      { code: "PP-3", desc: "SS & PVC Push Pull Magnet Big" },
      { code: "PP-4", desc: "Push Pull Magnet Big" },
    ] },
  { slug: "display-rod", name: "Display Rod", category: "door-fittings", codes: "DR-1 – DR-3",
    finishes: "SS", sizes: "Straight · with hook · bend",
    blurb: "Display rods for showrooms and shopfronts — straight, hooked and bend patterns.",
    variants: [
      { code: "DR-1", desc: "Display Rod" },
      { code: "DR-2", desc: "Display Rod With Hook" },
      { code: "DR-3", desc: "Bend Display Rod" },
    ] },
  { slug: "safety-door-chain", name: "Safety Door Chain", category: "door-fittings", codes: "DC-1 – DC-3",
    finishes: "SS · AB", sizes: "Big · small · concil",
    blurb: "Safety chains in big and small sizes, plus the concealed 'concil' chain.",
    variants: [
      { code: "DC-1", desc: "Safety Door Chain Big" },
      { code: "DC-2", desc: "Safety Door Chain Big AB" },
      { code: "DC-3", desc: "Safety Door Chain Small" },
      { code: "—", desc: "Concil Door Chain SS / AB" },
    ] },
  { slug: "door-closer", name: "Door Closer & Guard", category: "door-fittings", codes: "—",
    finishes: "Standard", sizes: "Capsule · spring · U type",
    blurb: "Capsule and spring door closers, with the U-type door guard.",
    variants: [
      { code: "—", desc: "Capsule Door Closer" },
      { code: "—", desc: "Spring Door Closer" },
      { code: "—", desc: "Door Guard U Type" },
    ] },
  { slug: "corner-protector", name: "Corner Protector", category: "door-fittings", codes: "CP-1",
    finishes: "Standard", sizes: "Square · round",
    blurb: "Protects furniture corners in transit and in use.",
    variants: [
      { code: "CP-1", desc: "Corner Protector" },
      { code: "—", desc: "Corner Protector Round" },
    ] },
  { slug: "buffer-pitcher-clamp", name: "Buffer & Pitcher Clamp", category: "door-fittings", codes: "B-1 · MF-1",
    finishes: "Standard", sizes: "Standard",
    blurb: "Door buffer and the male-female pitcher clamp.",
    variants: [
      { code: "B-1", desc: "Buffer" },
      { code: "MF-1", desc: "Male Female Pitcher Clamp" },
      { code: "—", desc: "Slim Magnet" },
    ] },

  /* ------------- LOCKS ------------- */
  { slug: "biscuit-lock", name: "Biscuit Lock", category: "locks", codes: "SL-1",
    finishes: "Standard", sizes: "Standard",
    blurb: "Sliding-door biscuit lock with keys.",
    variants: [ { code: "SL-1", desc: "Biscuit Lock" } ] },
  { slug: "popat-lock", name: "Popat Lock", category: "locks", codes: "SL-2",
    finishes: "Standard", sizes: "Standard",
    blurb: "The classic popat cupboard lock.",
    variants: [ { code: "SL-2", desc: "Popat Lock" } ] },
  { slug: "sliding-glass-lock", name: "Sliding Glass Lock", category: "locks", codes: "SL-3",
    finishes: "Standard", sizes: "Standard",
    blurb: "Keyed lock for sliding glass showcases.",
    variants: [ { code: "SL-3", desc: "Sliding Glass Lock" } ] },
  { slug: "glass-lock-range", name: "Glass Lock Range", category: "locks", codes: "GL-1 – GL-5", featured: true,
    finishes: "Standard", sizes: "Single · double",
    blurb: "Locks for frameless glass — glass-to-glass and glass-to-wood, single and double.",
    variants: [
      { code: "GL-1", desc: "Glass to Glass Single Lock" },
      { code: "GL-2", desc: "Glass to Glass Double Lock" },
      { code: "GL-3", desc: "Glass to Wood Single Lock" },
      { code: "GL-4", desc: "Glass Single Lock" },
      { code: "GL-5", desc: "Glass Double Lock" },
    ] },
  { slug: "multi-lock", name: "Multi Lock", category: "locks", codes: "ML-1 · ML-2",
    finishes: "Iron · standard", sizes: "Standard",
    blurb: "Elephant and iron multi-locks for heavier duty.",
    variants: [
      { code: "ML-1", desc: "Elephant Multi Lock" },
      { code: "ML-2", desc: "Iron Multi Lock" },
    ] },
  { slug: "cam-lock", name: "Cam & Inter Lock", category: "locks", codes: "CL-1 · CL-6",
    finishes: "Standard", sizes: "20 mm · 25 mm",
    blurb: "Cam locks in 20 and 25 mm barrel lengths, plus inter lock.",
    variants: [
      { code: "CL-1", desc: "Cam Lock 20mm, 25mm" },
      { code: "CL-6", desc: "Inter Lock" },
    ] },
  { slug: "aluminium-window-lock", name: "Aluminium Window Lock", category: "locks", codes: "AW-1 · AW-2",
    finishes: "Standard", sizes: "Left / right · 2-way",
    blurb: "Window locks for aluminium sections — handed and two-way patterns.",
    variants: [
      { code: "AW-1", desc: "Aluminium Window Lock (Left / Right)" },
      { code: "AW-2", desc: "Aluminium Window Lock (2 Way)" },
    ] },
  { slug: "iron-lock", name: "Iron Lock", category: "locks", codes: "PL-1",
    finishes: "Iron", sizes: "32 · 38 · 50 · 63 mm",
    blurb: "General-purpose iron locks in four sizes.",
    variants: [ { code: "PL-1", desc: "Iron Lock (Size 32, 38, 50, 63mm)" } ] },
  { slug: "brass-bag-lock", name: "Brass Bag Lock", category: "locks", codes: "PL-2",
    finishes: "Brass", sizes: "Standard",
    blurb: "Small brass lock for bags and cases.",
    variants: [ { code: "PL-2", desc: "Brass Bag Lock" } ] },
  { slug: "ss-pad-lock", name: "SS Pad Lock", category: "locks", codes: "PL-3",
    finishes: "SS", sizes: "2\" · 2½\" · 3\" · 4\" · 5\"",
    blurb: "Stainless pad locks from two to five inches.",
    variants: [ { code: "PL-3", desc: "SS Pad Lock (Size 2\", 2 1/2\", 3\", 4\", 5\")" } ] },

  /* ------------- HINGES ------------- */
  { slug: "hydraulic-hinges", name: "Hydraulic Hinges", category: "hinges", codes: "AH-1 – AH-3", featured: true,
    finishes: "Iron · SS · bush", sizes: "Standard",
    blurb: "Soft-closing hydraulic cup hinges — iron, stainless and bush types.",
    variants: [
      { code: "AH-1", desc: "Iron Hydraulic Hinges" },
      { code: "AH-2", desc: "S S Hydraulic Hinges" },
      { code: "AH-3", desc: "Bush Hydraulic Hinges" },
    ] },
  { slug: "auto-close-hinges", name: "Auto Close Hinges", category: "hinges", codes: "AH-4 – AH-6",
    finishes: "Iron · SS", sizes: "Standard · short arm",
    blurb: "Self-closing cup hinges, including the short-arm pattern.",
    variants: [
      { code: "AH-4", desc: "Iron Auto Close Hinges" },
      { code: "AH-5", desc: "SS Auto Close Hinges" },
      { code: "AH-6", desc: "Short Arm Hinges" },
    ] },
  { slug: "glass-hinges", name: "SS Glass Hinges", category: "hinges", codes: "HIN-1 – HIN-3",
    finishes: "SS", sizes: "6 mm · 8 mm glass",
    blurb: "Glass-door hinges for 6 and 8 mm panes, including the royal pattern.",
    variants: [
      { code: "HIN-1", desc: "SS Glass Hinges (Size 6mm, 8mm)" },
      { code: "HIN-2", desc: "Royal Glass Hinges" },
      { code: "HIN-3", desc: "Glass Hinges" },
    ] },
  { slug: "pivot-hinges", name: "Pivot Hinges", category: "hinges", codes: "HIN-4 · HIN-5",
    finishes: "SS", sizes: "Standard",
    blurb: "Pivot hinges — plain and with built-in magnet catch.",
    variants: [
      { code: "HIN-4", desc: "Pivot Hinges" },
      { code: "HIN-5", desc: "Pivot Hinges With Magnet" },
    ] },
  { slug: "bearing-flush-hinges", name: "Bearing & Flush Hinges", category: "hinges", codes: "HIN-6 · HIN-7",
    finishes: "SS · iron gold / AB", sizes: "4\" · 5\"",
    blurb: "Ball-bearing and flush butt hinges in four and five inch.",
    variants: [
      { code: "HIN-6", desc: "Bearing Hinges (Size 4\", 5\")" },
      { code: "HIN-7", desc: "Flush Hinges (Size 4\", 5\")" },
      { code: "—", desc: "Iron Hinges Gold / AB" },
    ] },
  { slug: "spring-hinges", name: "Spring Hinges (Soft Closing)", category: "hinges", codes: "—",
    finishes: "Standard", sizes: "4\" · 5\"",
    blurb: "Soft-closing spring hinges — 5\" spring and 4\" spring flush.",
    variants: [
      { code: "—", desc: "Spring Hinge (Size 5\") (Soft Closing)" },
      { code: "—", desc: "Spring Flush Hinges (Size 4\")" },
    ] },

  /* ------------- CHANNELS, WHEELS & GAS PUMPS ------------- */
  { slug: "gas-pump", name: "Gas Pump", category: "channels-wheels", codes: "GP-1 · GP-2", featured: true,
    finishes: "Standard · V Star", sizes: "5 · 10 · 15 · 20 · 25 · 30 · 35 kg",
    blurb: "Gas springs for lift-up shutters, in seven load ratings — standard and V Star.",
    variants: [
      { code: "GP-1", desc: "Gas Pump (5, 10, 15, 20, 25, 30, 35Kg)" },
      { code: "GP-2", desc: "Gas Pump V Star (5, 10, 15, 20, 25, 30, 35Kg)" },
    ] },
  { slug: "telescopic-channel", name: "Telescopic Channel", category: "channels-wheels", codes: "T-1 · T-2", featured: true,
    finishes: "Zinc dotted · SS · soft close", sizes: "60 – 75 g",
    blurb: "Drawer slides — zinc dotted 75 g, stainless 60 g and SS soft-close 60 g.",
    variants: [
      { code: "T-1", desc: "Zinc Dotted 75Gms Telescopic Channel" },
      { code: "T-2", desc: "Stainless Steel 60Gms Telescopic Channel" },
      { code: "—", desc: "SS Soft Close 60g" },
    ] },
  { slug: "friction-hinge", name: "Friction Hinge", category: "channels-wheels", codes: "FH-1",
    finishes: "Standard", sizes: "8\" · 10\" · 12\" · 14\" · 16\"",
    blurb: "Friction stays for top-hung aluminium windows, five sizes.",
    variants: [ { code: "FH-1", desc: "Friction Hinge (Size 8\", 10\", 12\", 14\", 16\")" } ] },
  { slug: "folding-bracket", name: "SS Folding Bracket", category: "channels-wheels", codes: "FOL-1",
    finishes: "SS", sizes: "10\" · 12\" · 14\" · 16\"",
    blurb: "Folding shelf brackets in stainless steel.",
    variants: [ { code: "FOL-1", desc: "Stainless Steel Folding Bracket (Size 10\", 12\", 14\", 16\")" } ] },
  { slug: "conceal-tower-bolt", name: "Conceal Tower Bolt", category: "channels-wheels", codes: "CTB-1",
    finishes: "Standard", sizes: "10\" rod",
    blurb: "Concealed tower bolt with 10-inch rod.",
    variants: [ { code: "CTB-1", desc: "Conceal Tower Bolt 10\" Rod" } ] },
  { slug: "soft-close-8-wheel", name: "Soft Close 8 Wheel & Channel", category: "channels-wheels", codes: "WHE-1 · WHE-3",
    finishes: "Standard", sizes: "Wheel + channel set",
    blurb: "Soft-closing 8-wheel sliding system with matching channel.",
    variants: [
      { code: "WHE-1", desc: "Soft Close 8 Wheel" },
      { code: "WHE-3", desc: "Soft Close 8 Wheel Channel" },
    ] },
  { slug: "taklu-wheel", name: "Taklu Wheel & Channel", category: "channels-wheels", codes: "WHE-2 – TRK-4",
    finishes: "Standard", sizes: "Heavy · light · single",
    blurb: "Taklu wheel systems in heavy, light and single patterns with soft-close channels.",
    variants: [
      { code: "WHE-2", desc: "Soft Close Taklu Wheel Heavy" },
      { code: "WHE-4", desc: "Soft Close Taklu Wheel Heavy Channel" },
      { code: "WHE-5", desc: "Soft Close Taklu Wheel Single Channel" },
      { code: "TRK-1", desc: "Taklu Wheel Heavy" },
      { code: "TRK-2", desc: "Taklu Wheel Light" },
      { code: "TRK-3", desc: "Soft Close Taklu Wheel Light Channel" },
      { code: "TRK-4", desc: "Taklu Wheel Single" },
    ] },

  /* ------------- KITCHEN ZALLI ------------- */
  { slug: "aluminium-kitchen-zalli", name: "Aluminium Kitchen Zalli", category: "kitchen-zalli", codes: "—", featured: true,
    finishes: "SS brush · black · rosegold", sizes: "Stepped cabinet sizes",
    blurb: "Ventilation zalli for kitchen cabinets in three premium finishes.",
    variants: [
      { code: "—", desc: "SS Brush" },
      { code: "—", desc: "Black" },
      { code: "—", desc: "Rosegold" },
    ] },
  { slug: "kitchen-jali-bend", name: "Bend Type Kitchen Jali", category: "kitchen-zalli", codes: "KJ-2",
    finishes: "SS", sizes: "80 × 150 · 200 · 250",
    blurb: "Bend-type jali in three widths, SS finish.",
    variants: [ { code: "KJ-2", desc: "Bend Type Kitchen Jali Size 80 x 150, 200, 250 — SS Finish" } ] },

  /* ------------- CONCEAL FITTINGS ------------- */
  { slug: "conceal-aluminium-handle", name: "Conceal Aluminium Handle SNCP", category: "conceal-fittings", codes: "CH-1", featured: true,
    finishes: "SNCP", sizes: "4\" · 6\" · 8\" · 10\" · 12\"",
    blurb: "Recessed aluminium handles in satin nickel, five sizes.",
    variants: [ { code: "CH-1", desc: "Conceal Aluminium Handle SNCP Finish (Size 4\", 6\", 8\", 10\", 12\")" } ] },
  { slug: "ss-concil", name: "SS Concil Heavy & Light", category: "conceal-fittings", codes: "CH-3 – CH-6 · S 112",
    finishes: "SS", sizes: "4\" · 6\"",
    blurb: "Stainless concil handles in heavy and light gauges.",
    variants: [
      { code: "CH-3", desc: "SS Concil Heavy (Size 4\", 6\")" },
      { code: "S 112", desc: "SS Concil Heavy" },
      { code: "CH-5", desc: "SS Concil Heavy" },
      { code: "CH-6", desc: "SS Concil Light" },
    ] },
  { slug: "shape-conceal", name: "Oval / Square / Round Conceal", category: "conceal-fittings", codes: "CON-1 – CON-4 · CHR-1",
    finishes: "Standard", sizes: "3\" · 4\" · 6\" · small & big",
    blurb: "Shaped conceal pulls in three sizes each.",
    variants: [
      { code: "CON-3", desc: "Oval Conceal (Size 3\", 4\", 6\")" },
      { code: "CON-4", desc: "Square Conceal (Size 3\", 4\", 6\")" },
      { code: "CHR-1", desc: "Round Conceal Small & Big" },
      { code: "CON-1", desc: "Conceal Tapper 3/4\", 1\"" },
    ] },
  { slug: "plate-ring-conceal", name: "Plate, Ring & WM Conceal", category: "conceal-fittings", codes: "CON-2 – CON-7",
    finishes: "Standard", sizes: "3/4\" · 1\"",
    blurb: "Plate, ring and WM conceals in three-quarter and one inch.",
    variants: [
      { code: "CON-5", desc: "Plate Conceal (Size 3/4\")" },
      { code: "CON-6", desc: "Plate Conceal (Size 1\")" },
      { code: "CON-7", desc: "Ring Conceal (Size 3/4\")" },
      { code: "CON-2", desc: "Ring Conceal (Size 1\")" },
      { code: "—", desc: "WM Conceal (Size 1\") · Ring Conceal (Light)" },
    ] },

  /* ------------- GLASS DOOR HANDLES ------------- */
  { slug: "h-type-handle", name: "'H' Type Handle", category: "glass-door-handles", codes: "GD-1 · GD-4 · GD-7", featured: true,
    finishes: "SS · crafted AB", sizes: "Round · square 25×25 mm",
    blurb: "The staple glass-door pull — standard, deluxe and square-section.",
    variants: [
      { code: "GD-1", desc: "'H' Type" },
      { code: "GD-4", desc: "Deluxe 'H' Type" },
      { code: "GD-7", desc: "Square 'H' Type (Size 25mm x 25mm)" },
    ] },
  { slug: "d-type-handle", name: "'D' Type Handle", category: "glass-door-handles", codes: "GD-2 · GD-5 · GD-8",
    finishes: "SS", sizes: "Round · square 40×20 · 25×25 mm",
    blurb: "'D' pulls in round and two square sections.",
    variants: [
      { code: "GD-2", desc: "'D' Type" },
      { code: "GD-5", desc: "Square 'D' Type (Size 40mm x 20mm)" },
      { code: "GD-8", desc: "Square 'D' Type (Size 25mm x 25mm)" },
    ] },
  { slug: "s-type-handle", name: "'S' Type Handle", category: "glass-door-handles", codes: "GD-3",
    finishes: "SS", sizes: "Standard",
    blurb: "Curved 'S' profile pull for glass doors.",
    variants: [ { code: "GD-3", desc: "'S' Type" } ] },
  { slug: "crafted-ab-handles", name: "Crafted AB Handles", category: "glass-door-handles", codes: "GD-9 · GD-10",
    finishes: "Antique brass", sizes: "'H' · 'D'",
    blurb: "Ornamental crafted pulls in antique brass finish.",
    variants: [
      { code: "GD-9", desc: "Crafted 'H' AB Finish" },
      { code: "GD-10", desc: "Crafted 'D' AB Finish" },
    ] },
  { slug: "glass-handle-with-lock", name: "Glass Door Handle With Lock", category: "glass-door-handles", codes: "GD-6",
    finishes: "SS", sizes: "600 mm",
    blurb: "600 mm pull handle with integrated lock for glass entrance doors.",
    variants: [ { code: "GD-6", desc: "Glass Door Handle With Lock (Size 600mm)" } ] },

  /* ------------- KNOBS ------------- */
  { slug: "crystal-knob", name: "Crystal & Cristal Knob", category: "knobs", codes: "K-1", featured: true,
    finishes: "Clear acrylic", sizes: "No. 1 · 2 · 3 · 920 · 930",
    blurb: "Faceted acrylic crystal knobs in three sizes plus the cristal 920 / 930.",
    variants: [
      { code: "—", desc: "Crystal Knob 1, 2, 3" },
      { code: "K-1", desc: "Cristal Knob 920, 930" },
    ] },
  { slug: "cateye-mirror-knob", name: "Cateye & Mirror Knob", category: "knobs", codes: "—",
    finishes: "Acrylic", sizes: "1¼ · 1½ · 3 – 6",
    blurb: "Cateye pattern and mirror-face knobs across six sizes.",
    variants: [
      { code: "—", desc: "Cateye Knob" },
      { code: "—", desc: "Mirror Knob 1.1/4, 1.1/2, 3, 4, 5, 6" },
    ] },
  { slug: "cut-design-knob", name: "Cut Design & Colour Knobs", category: "knobs", codes: "—",
    finishes: "Acrylic · colours", sizes: "3 – 6",
    blurb: "Cut-facet designs and colour knobs (R/W, T/W and more).",
    variants: [
      { code: "—", desc: "Cut Design Knob 3, 4, 5, 6" },
      { code: "—", desc: "Colour Knobs R/W, T/W… etc" },
    ] },
  { slug: "royal-rose-knobs", name: "Royal & Rose Knobs", category: "knobs", codes: "K-2 – K-5",
    finishes: "CP · gold · black · white · antique", sizes: "8013 · 8014 · 8023",
    blurb: "Royal series and rose knobs in premium plated finishes.",
    variants: [
      { code: "K-2", desc: "Royal Knob T/W, B.R., V.R." },
      { code: "K-3", desc: "8013 Black / White" },
      { code: "K-4", desc: "8014 Rose Knob CP / Gold" },
      { code: "K-5", desc: "8023 CP / Antique" },
    ] },
  { slug: "hooks-runners", name: "Cloth Hook, Dust Protector & Glass Runner", category: "knobs", codes: "MO-1 · DP-1 · GR-1",
    finishes: "Standard", sizes: "Double · single",
    blurb: "Cloth hooks, dust protectors and glass runners.",
    variants: [
      { code: "MO-1", desc: "Cloth Hook Double / Single" },
      { code: "DP-1", desc: "Dust Protector" },
      { code: "GR-1", desc: "Glass Runner" },
    ] },

  /* ------------- GLASS FITTINGS ------------- */
  { slug: "mirror-caps-brackets", name: "Mirror Caps & Brackets", category: "glass-fittings", codes: "G1 – G4",
    finishes: "Standard", sizes: "Dome 20 · 25 · half / full",
    blurb: "Mirror caps, dome caps and half/full mirror brackets.",
    variants: [
      { code: "G1", desc: "Mirror Cap" },
      { code: "G2", desc: "Mirror Bracket Half / Full" },
      { code: "G3", desc: "Mirror Bracket" },
      { code: "G4", desc: "Dome Mirror Cap (Size 20, 25)" },
    ] },
  { slug: "sumo-bracket", name: "Sumo Bracket", category: "glass-fittings", codes: "SB-1", featured: true,
    finishes: "SS · CP", sizes: "XS · S · M · L",
    blurb: "Heavy shelf brackets in four sizes, SS and chrome.",
    variants: [ { code: "SB-1", desc: "Sumo Bracket SS & CP Finish (Size XS, S, M, L)" } ] },
  { slug: "glass-stud-partition", name: "Glass Stud & Partition Bracket", category: "glass-fittings", codes: "PB-1",
    finishes: "SS", sizes: "3/4\" · 1\" · 6 / 8 / 12 mm",
    blurb: "Glass studs, partition brackets and capsule glass brackets.",
    variants: [
      { code: "—", desc: "Glass Stud (Size 3/4\" / 1\")" },
      { code: "PB-1", desc: "Partition Bracket" },
      { code: "—", desc: "Capsule Glass Bracket (Size 6, 8, 12mm)" },
    ] },
  { slug: "l-vacuum-range", name: "'L' Vacuum Range", category: "glass-fittings", codes: "LV-1 – LV-4",
    finishes: "SS · CP · acrylic", sizes: "Heavy · light",
    blurb: "'L' vacuums from light acrylic to heavy stainless.",
    variants: [
      { code: "LV-1", desc: "Acrylic 'L' Vacuum" },
      { code: "LV-2", desc: "'L' Vacuum Light" },
      { code: "LV-3", desc: "'L' Vacuum Heavy CP / SS" },
      { code: "LV-4", desc: "'L' Vacuum Heavy" },
    ] },
  { slug: "l-clamp-range", name: "SS 'L' Clamp Range", category: "glass-fittings", codes: "LC-1 – LC-3",
    finishes: "SS", sizes: "20 – 80 mm (2 – 3 mm thick)",
    blurb: "Square and round 'L' clamps, including double-hole heavy and glass-connector types.",
    variants: [
      { code: "LC-1", desc: "SS 'L' Clamp 20, 25, 30, 40 (2mm) · 50, 80 (3mm)" },
      { code: "LC-2", desc: "'L' Clamp Sq & Round With Glass Connector" },
      { code: "LC-3", desc: "SS 'L' Clamp Double Hole Heavy" },
    ] },
  { slug: "folding-glass-bracket", name: "SS Folding Glass Bracket & Connector", category: "glass-fittings", codes: "FB-1 – FB-4",
    finishes: "SS", sizes: "Standard",
    blurb: "Folding glass brackets and the square glass connector.",
    variants: [
      { code: "FB-1", desc: "SS Folding Glass Bracket" },
      { code: "FB-2", desc: "SS Folding Glass Bracket" },
      { code: "FB-3", desc: "SS Square Glass Connector" },
      { code: "FB-4", desc: "SS Folding Glass Bracket" },
    ] },

  /* ------------- MAIN DOOR HANDLES ------------- */
  { slug: "classic-main-door-handles", name: "Classic Main Door Handles", category: "main-door-handles", codes: "MDH-1 – MDH-6", featured: true,
    finishes: "SS · AB · CP · copper", sizes: "150 · 190 · 230 · 360 · 380",
    blurb: "The classic main-door handle series in stainless and antique brass, plus CP and copper patterns.",
    variants: [
      { code: "MDH-1", desc: "230 SS & AB" },
      { code: "MDH-2", desc: "360 SS & AB" },
      { code: "MDH-3", desc: "380 SS & AB" },
      { code: "MDH-4", desc: "190 SS & AB" },
      { code: "MDH-5", desc: "8038 CP / 1101 Copper" },
      { code: "MDH-6", desc: "150 SS & AB" },
    ] },
  { slug: "98-series-handles", name: "98 Series Handles", category: "main-door-handles", codes: "MDH-7 – MDH-9",
    finishes: "SS · AB", sizes: "9803 · 9811 · 9812 · 9821",
    blurb: "The 98-series decorative main-door handles.",
    variants: [
      { code: "MDH-7", desc: "9821 SS & AB" },
      { code: "MDH-8", desc: "9811 AB" },
      { code: "MDH-9", desc: "9812 AB · 9803 AB" },
    ] },
  { slug: "square-d-handle", name: "Square 'D' Handle 25 × 25", category: "main-door-handles", codes: "MDH-10",
    finishes: "SS", sizes: "8 · 10 · 12 · 15 · 18 · 24\"…",
    blurb: "Square-section 'D' pull in lengths from 8 to 24 inch and beyond.",
    variants: [ { code: "MDH-10", desc: "25 x 25mm Square 'D' Handle (Size: 8, 10, 12, 15, 18, 24…)" } ] },
  { slug: "d-handle-40x10", name: "'D' Handle 40 × 10", category: "main-door-handles", codes: "MDH-11",
    finishes: "SS", sizes: "8 – 24\"…",
    blurb: "Flat-section 'D' pull, 40 × 10 mm.",
    variants: [ { code: "MDH-11", desc: "40 x 10 'D' Handle (Size: 8, 10, 12, 15, 18, 24…)" } ] },
  { slug: "square-h-handles", name: "Square 'H' Handles", category: "main-door-handles", codes: "MDH-12 – MDH-14",
    finishes: "SS", sizes: "8 – 24\"… · 40×8 · 25×25 mm",
    blurb: "'H' pattern pulls in two square sections.",
    variants: [
      { code: "MDH-12", desc: "40 x 8mm Square 'H' Handle (Size: 8 – 24…)" },
      { code: "MDH-13", desc: "25 x 25mm Square 'H' Handle (Size: 8 – 24…)" },
      { code: "MDH-14", desc: "Square 'H' Handle" },
    ] },

  /* ------------- CABINET HANDLES ------------- */
  { slug: "cabinet-series-a", name: "Cabinet Handles — Series A", category: "cabinet-handles", codes: "CAB-1 – CAB-8", featured: true,
    finishes: "Assorted", sizes: "96 – 224 mm",
    blurb: "Eight patterns: 8010, 212, 5336, 868, 2005, 888, 7268 and 900.",
    variants: [
      { code: "CAB-1", desc: "8010 (Size 96, 128, 160, 224mm)" },
      { code: "CAB-2", desc: "212 (Size 96, 128, 160mm)" },
      { code: "CAB-3", desc: "5336 (Size 64 – 224mm)" },
      { code: "CAB-4", desc: "868 (Size 96, 128, 160mm)" },
      { code: "CAB-5", desc: "2005 (Size 96 – 192mm)" },
      { code: "CAB-6", desc: "888 (Size 96, 128, 160mm)" },
      { code: "CAB-7", desc: "7268 (Size 96 – 192mm)" },
      { code: "CAB-8", desc: "900 (Size 96 – 224mm)" },
    ] },
  { slug: "cabinet-series-b", name: "Cabinet Handles — Series B", category: "cabinet-handles", codes: "CAB-9 – CAB-15",
    finishes: "Assorted", sizes: "96 – 224 mm",
    blurb: "Seven patterns: 6352, 602, 6872, 512, 8037, 509 and 551.",
    variants: [
      { code: "CAB-9", desc: "6352 (Size 96 – 224mm)" },
      { code: "CAB-10", desc: "602 (Size 96, 128, 160mm)" },
      { code: "CAB-11", desc: "6872 (Size 128 – 224mm)" },
      { code: "CAB-12", desc: "512 (Size 128, 160, 192mm)" },
      { code: "CAB-13", desc: "8037 (Size 96 – 224mm)" },
      { code: "CAB-14", desc: "509 (Size 96 – 192mm)" },
      { code: "CAB-15", desc: "551 (Size 96 – 224mm)" },
    ] },
  { slug: "cabinet-series-c", name: "Cabinet Handles — Series C", category: "cabinet-handles", codes: "CAB-16 – CAB-19",
    finishes: "Assorted", sizes: "96 – 224 mm",
    blurb: "AZ 02, 2768, 3024, 3044 and 6806 patterns.",
    variants: [
      { code: "CAB-16", desc: "AZ 02 (Size 4 – 12)" },
      { code: "CAB-17", desc: "2768 (Size 128, 160, 192mm)" },
      { code: "CAB-18", desc: "3024 (Size 96 – 224mm)" },
      { code: "CAB-19", desc: "3044 (Size 96 – 224mm) · 6806 (96 – 192mm)" },
    ] },
  { slug: "ss-handle-range", name: "SS Handle Range", category: "cabinet-handles", codes: "SS-1 – SS-9",
    finishes: "SS", sizes: "4 · 6 · 8 · 10 · 12",
    blurb: "KN, AZ, HRD and 'D' patti stainless handles, all in five sizes.",
    variants: [
      { code: "SS-1", desc: "KN 02" }, { code: "SS-2", desc: "HRD Bend" },
      { code: "SS-3", desc: "AZ 01" }, { code: "SS-4", desc: "12\" x 6\" 'D' Patti Handle" },
      { code: "SS-5", desc: "HRD 3 Ring" }, { code: "SS-6", desc: "12\" x 8\" 'D' Bend Handle" },
      { code: "SS-7", desc: "KN 01" }, { code: "SS-8", desc: "Royal 'D' Patti" },
      { code: "SS-9", desc: "AZ 02" },
    ] },

  /* ------------- GENERAL HARDWARE ------------- */
  { slug: "pvc-clamps-buttons", name: "PVC Clamps & Buttons", category: "general-hardware", codes: "CC-1 · CC-2 · CLIP-1",
    finishes: "Clear · white", sizes: "4 mm · 6 mm",
    blurb: "PVC corner clamps, center folds and buttons for glass display cases.",
    variants: [
      { code: "CC-1", desc: "PVC Corner Clamp Clear & White (4mm / 6mm)" },
      { code: "CC-2", desc: "PVC Center Fold Clear & White (4mm / 6mm)" },
      { code: "CLIP-1", desc: "PVC Button Clear & White (4mm / 6mm)" },
    ] },
  { slug: "cable-managers", name: "Cable Managers", category: "general-hardware", codes: "CM-1 – CM-4",
    finishes: "PVC · WM", sizes: "50 · 60 · 75 mm",
    blurb: "Desk cable managers in PVC and WM, three diameters.",
    variants: [
      { code: "CM-1", desc: "WM Cable Manager 60 & 75" },
      { code: "CM-2", desc: "PVC Cable Manager 60mm" },
      { code: "CM-3", desc: "PVC Cable Manager 50, 60" },
      { code: "CM-4", desc: "PVC Cable Manager 50, 60 & 75" },
    ] },
  { slug: "sliding-latch", name: "Sliding Latches", category: "general-hardware", codes: "SL-4",
    finishes: "Standard", sizes: "Big · small · bend type",
    blurb: "Sliding latches including the bend type.",
    variants: [
      { code: "SL-4", desc: "Sliding Latch Big & Small" },
      { code: "—", desc: "Sliding Latch Bend Type" },
    ] },
  { slug: "sofa-legs", name: "Sofa Legs", category: "general-hardware", codes: "SOF-1 · SOF-2",
    finishes: "PVC · standard", sizes: "50×80 · 100 · 120",
    blurb: "PVC and standard sofa legs in three heights.",
    variants: [
      { code: "SOF-1", desc: "PVC Sofa Leg" },
      { code: "SOF-2", desc: "Sofa Leg (Size 50x80, 100, 120)" },
    ] },
  { slug: "baby-latch", name: "Baby Latch", category: "general-hardware", codes: "BL-1 – BL-3",
    finishes: "Standard", sizes: "3\" · 4\" · S / M / B",
    blurb: "Baby latches — push open, deluxe heavy and standard in three sizes.",
    variants: [
      { code: "BL-1", desc: "Push Open Baby Latch (Size 3\", 4\")" },
      { code: "BL-2", desc: "Baby Latch (Size 4\" Deluxe Heavy)" },
      { code: "BL-3", desc: "Baby Latch (Size Small, Medium, Big)" },
    ] },
  { slug: "bed-fitting-glass-cutter", name: "Bed Fitting & Glass Cutter", category: "general-hardware", codes: "BF-1 · GC-1",
    finishes: "Standard", sizes: "Standard",
    blurb: "Bed connection fittings and glass cutters.",
    variants: [
      { code: "BF-1", desc: "Bed Fitting" },
      { code: "GC-1", desc: "Glass Cutter" },
    ] },
  { slug: "l-pipe-support", name: "'L' Pipe Support & Concil Bend", category: "general-hardware", codes: "BB-1 · BB-2",
    finishes: "Standard", sizes: "3/4\" · 1\"",
    blurb: "Pipe supports and concil bends in two bores.",
    variants: [
      { code: "BB-1", desc: "'L' Pipe Support (Size 3/4\", 1\")" },
      { code: "BB-2", desc: "'L' Concil Bend (Size 3/4\", 1\")" },
    ] },
  { slug: "datta-buffer", name: "Datta & Buffers", category: "general-hardware", codes: "—",
    finishes: "Standard · solid", sizes: "1/2\" – 4\" · No. 1 – 8",
    blurb: "Datta in half to four inch (plain and solid) and buffers No. 1 through 8.",
    variants: [
      { code: "—", desc: "Datta 1/2\", 3/4\", 1\", 1 1/4\", 1 1/2\", 2\", 2 1/2\", 3\", 4\"" },
      { code: "—", desc: "Solid Datta 1 1/2\", 2\", 2 1/2\", 3\", 4\" · Half / Full Solid" },
      { code: "—", desc: "Buffer No. 1 – 8" },
    ] },
  { slug: "curtain-rings-runners", name: "Curtain Rings & Runners", category: "general-hardware", codes: "—",
    finishes: "Assorted", sizes: "25 – 50 mm · No. 0 – 6",
    blurb: "Royal, super deluxe and jumbo rings, runners with plastic or metal hook, guides and glass vacuums.",
    variants: [
      { code: "—", desc: "Curtain Ring No. 0 – 6 (incl. 0+ / 0++)" },
      { code: "—", desc: "Royal Ring · Super Deluxe · Jumbo Ring (25 – 50mm)" },
      { code: "—", desc: "Runner with Plastic / Metal Hook · Guide" },
      { code: "—", desc: "Concil Oval Deluxe Ring · Glass Vaccum · Wall Plug" },
    ] },
  { slug: "dowell-clip", name: "Dowell, Clip Catcher & Screw Caps", category: "general-hardware", codes: "D-1 · SC-1 · WP-1",
    finishes: "Standard", sizes: "8 × 35 / 40",
    blurb: "Dowells, clip catchers, screw caps, crab wall plugs and silencer dots.",
    variants: [
      { code: "D-1", desc: "Dowell (Size 8x35/40)" },
      { code: "—", desc: "Clip Catcher" },
      { code: "SC-1", desc: "Screw Cap" },
      { code: "WP-1", desc: "Crab Wall Plug" },
      { code: "SD-1", desc: "Silencer Dot" },
    ] },
];

export function catName(slug) {
  const c = CATEGORIES.find((x) => x.slug === slug);
  return c ? c.name : slug;
}
export function catImg(slug) {
  const c = CATEGORIES.find((x) => x.slug === slug);
  return c ? c.img : "";
}
export function enquireHref(p) {
  const subj = p ? "Enquiry: " + p.name + " (" + p.codes + ")" : "Enquiry from website";
  const body = p
    ? "Hello Oberoi Enterprise,%0D%0A%0D%0APlease send availability and a quote for:%0D%0AProduct: " +
      encodeURIComponent(p.name) + "%0D%0ACode(s): " + encodeURIComponent(p.codes) +
      "%0D%0ASize / finish: %0D%0AQuantity: %0D%0A%0D%0AThank you."
    : "";
  return "mailto:" + SITE.email + "?subject=" + encodeURIComponent(subj) + (body ? "&body=" + body : "");
}
export function waHref(p) {
  const t = p ? "Enquiry about " + p.name + " (" + p.codes + ")" : "Enquiry from Oberoi Enterprise website";
  return "https://wa.me/" + SITE.whatsapp + "?text=" + encodeURIComponent(t);
}

/* also expose as globals */
if (typeof window !== "undefined") {
  window.OBEROI = { SITE, CATEGORIES, PRODUCTS, catName, catImg, enquireHref, waHref };
}
